baseURL = 'https://purcuino.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Who We Are"
    url = "/who-we-are"
    weight = 20

  [[menu.main]]
    name = "What We Do"
    url = "/what-we-do"
    weight = 30

  [[menu.main]]
    name = "Benefits"
    url = "/benefits"
    weight = 40

  [[menu.main]]
    name = "Careers"
    url = "/careers"
    weight = 50

  [[menu.main]]
    name = "Contact Us"
    url = "/contact-us"
    weight = 60
